// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEV64ztJ1i9Or4pNJLGkJ2_wECvHy7LMY',
    appId: '1:536721750046:web:9ea36b49048b3a983a160f',
    messagingSenderId: '536721750046',
    projectId: 'silver-track-project',
    authDomain: 'silver-track-project.firebaseapp.com',
    storageBucket: 'silver-track-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzb3WDVsINcHUhef0LfAfjH9PG2xKPw58',
    appId: '1:536721750046:android:6a8cff3a97a247763a160f',
    messagingSenderId: '536721750046',
    projectId: 'silver-track-project',
    storageBucket: 'silver-track-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3eYiB2wWATMzCFfOLx4E-uzyp0yeFcfQ',
    appId: '1:536721750046:ios:58273cb57707d1ab3a160f',
    messagingSenderId: '536721750046',
    projectId: 'silver-track-project',
    storageBucket: 'silver-track-project.firebasestorage.app',
    iosBundleId: 'com.example.jewelryLedger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3eYiB2wWATMzCFfOLx4E-uzyp0yeFcfQ',
    appId: '1:536721750046:ios:58273cb57707d1ab3a160f',
    messagingSenderId: '536721750046',
    projectId: 'silver-track-project',
    storageBucket: 'silver-track-project.firebasestorage.app',
    iosBundleId: 'com.example.jewelryLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEV64ztJ1i9Or4pNJLGkJ2_wECvHy7LMY',
    appId: '1:536721750046:web:7c7eaff4916f42a33a160f',
    messagingSenderId: '536721750046',
    projectId: 'silver-track-project',
    authDomain: 'silver-track-project.firebaseapp.com',
    storageBucket: 'silver-track-project.firebasestorage.app',
  );

}